"""Add updated_at to LessonLearned

Revision ID: 6be788b28fb0
Revises: 6de6914e9a76
Create Date: 2025-08-13 21:42:39.429437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be788b28fb0'
down_revision = '6de6914e9a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons_learned', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons_learned', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
