"""Add IP address and user agent to ReadLog

Revision ID: 88caef8bfdb7
Revises: 6be788b28fb0
Create Date: 2025-08-24 17:14:00.678919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88caef8bfdb7'
down_revision = '6be788b28fb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('read_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('read_logs', schema=None) as batch_op:
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
